version: '3.8'

name: music-geolocalizer

services:
  # backend
  backend: 
    stdin_open: true
    tty: true
    container_name: backend-dev
    build: 
      context: ./services/backend
      dockerfile: Dockerfile_dev
    ports:
      - 8000:8000
      - 5678:5678 # debug
    volumes:
      - type: bind
        source: ${MUSIC_LIBRARY_PATH}
        target: /music
        read_only: true
      - ./services/backend:/app
      - ./data:/data
    environment:
      - GDAL_LIBRARY_PATH=/usr/lib/ogdi/4.1/libgdal.so
      - MUSIC_PATH_MAX_LENGTH=${MUSIC_PATH_MAX_LENGTH}
    depends_on:
      - db
      - nginx
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music
    ports:
      - 54333:5432
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
      - ./services/migration_install.sql:/docker-entrypoint-initdb.d/migration_install.sql

  nginx:
    image: nginx:stable-alpine3.19-perl
    container_name: nginx-dev
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: ${MUSIC_LIBRARY_PATH}
        target: /music
        read_only: true
      - ./services/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-dev
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile_dev
    ports:
      - 3000:3000
    profiles:
      - front