FROM python:3.12

# don't bufferize python logs
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
# COPY ./requirements_dev.txt /app/requirements_dev.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
# RUN pip install --no-cache-dir --upgrade -r /app/requirements_dev.txt

CMD ["./run_dev.sh"]