FROM python:3.12

# don't bufferize python logs
ENV PYTHONUNBUFFERED 1

ENV PYTHONPATH=$PYTHONPATH:/app/backend-django

WORKDIR /app

# Install GDAL
RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin

RUN apt-get install redis -y

COPY ./requirements.txt /app/requirements.txt
COPY ./requirements_dev.txt /app/requirements_dev.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements_dev.txt

CMD ["/app/run_dev.sh"]