# Use an official Node runtime as the base image
FROM node:22-alpine3.20

# Set the working directory in the container to /app
WORKDIR /app

COPY . .

# Install any needed packages specified in package.json
RUN npm install

RUN npm run build

CMD npm run dev