# Generated by Django 5.0.6 on 2024-06-12 10:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': '"library"."artist"',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': '"library"."genre"',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(null=True, verbose_name='date published')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_ALBUM_ARTIST', to='filesystem.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_ALBUM_GENRE', to='filesystem.genre')),
            ],
            options={
                'db_table': '"library"."album"',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('path', models.TextField(max_length='500')),
                ('track', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('bpm', models.IntegerField(null=True)),
                ('last_played', models.DateTimeField(null=True, verbose_name='last time played song')),
                ('count_played', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
                ('checksum', models.TextField(null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_MUSIC_ALBUM', to='filesystem.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_MUSIC_ARTIST', to='filesystem.artist')),
            ],
            options={
                'db_table': '"library"."music"',
            },
        ),
    ]
