# Generated by Django 5.0.6 on 2024-06-18 18:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country_name', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('last_played', models.DateTimeField(null=True, verbose_name='last time played artist')),
                ('count_played', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_played', models.DateTimeField(null=True, verbose_name='last time played genre')),
                ('count_played', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(null=True, verbose_name='date published')),
                ('last_played', models.DateTimeField(null=True, verbose_name='last time played album')),
                ('count_played', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_ALBUM_ARTIST', to='music.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_ALBUM_GENRE', to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('path', models.TextField(max_length='500')),
                ('track', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('bpm', models.IntegerField(null=True)),
                ('last_played', models.DateTimeField(null=True, verbose_name='last time played song')),
                ('count_played', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
                ('checksum', models.TextField(null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_MUSIC_ALBUM', to='music.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_MUSIC_ARTIST', to='music.artist')),
            ],
        ),
    ]
